### PR TITLE
add support for converting celsius to fahrenheit

### PR DESCRIPTION
**Pull request by masneyb**
use the newly introduced function convert_value() in fit4ruby to convert celsius to fahrenheit

### CODE REVIEW

**Comment by masneyb** [comment]
This patch depends on this change to fit4ruby: https://github.com/scrapper/fit4ruby/pull/26

**Comment by masneyb** [comment]
@scrapper : I rebased my code against your latest main branch and updated my branch to use your new `conversion_offset()`. CI is failing due to the following error:

```
 undefined method `conversion_offset' for #<PostRunner::ActivityListView:0x0000563465c61548>
```

I suspect the issue is that you will need to publish a new version of fit4ruby with the latest code.

**Comment by scrapper** [comment]
I've released a new version of fit4ruby (3.11.0). This should fix the above error. If so, please re-open the pull request and I'm happy to merge it.

**Comment by masneyb** [comment]
@scrapper : I rebased my MR and everything looks good now.

**Pull request merged**
